conll_data = [
    "Tôi O",
    "đang O",
    "tìm O",
    "một O",
    "chiếc O",
    "laptop B-device_name",
    "Dell B-brand",
    "với O",
    "CPU O",
    "Intel B-cpu_name",
    "i5 I-cpu_name",
    "và O",
    "RAM O",
    "8GB B-ram",
    "",
    "Chiếc O",
    "máy O",
    "tính O",
    "Acer B-brand",
    "này O",
    "có O",
    "màn B-screen_size",
    "hình I-screen_size",
    "15 I-screen_size",
    "inch I-screen_size",
    "và O",
    "độ B-screen_resolution",
    "phân I-screen_resolution",
    "giải I-screen_resolution",
    "1920x1080 I-screen_resolution",
    "",
    "Tôi O",
    "muốn O",
    "một O",
    "chiếc O",
    "laptop B-device_name",
    "nhẹ O",
    "khoảng O",
    "1.5 B-weight",
    "kg I-weight",
    ""
]

# Ghi vào file
with open("dataset.conll", "w", encoding="utf-8") as f:
    f.write("\n".join(conll_data))
